# Generated by Django 4.2.6 on 2023-12-25 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='description',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='description',
            new_name='name',
        ),
    ]
