# Generated by Django 4.2.6 on 2023-12-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_description_answers_answer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Categories',
        ),
        migrations.AddField(
            model_name='quizs',
            name='quizCategories',
            field=models.ManyToManyField(to='backend.categories'),
        ),
        migrations.DeleteModel(
            name='QuizsCategorys',
        ),
    ]
