# Generated by Django 4.2.6 on 2024-01-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_categorys_categories_quizs_quizcategories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizs',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
