# Generated by Django 4.2.6 on 2024-01-19 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0004_quizs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizResults', to='backend.quizs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userResults', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.ManyToManyField(to='backend.answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to='backend.questions')),
                ('quizResult', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to='backend.quizresults')),
            ],
        ),
    ]
