# Generated by Django 4.2.6 on 2024-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_quizresults_useranswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-20T16:36'),
            preserve_default=False,
        ),
    ]
