# Generated by Django 4.2.6 on 2024-01-22 17:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_quizresults_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizs',
            name='quizCategories',
        ),
        migrations.AddField(
            model_name='quizs',
            name='quizCategory',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='quizCategory', to='backend.categories'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizresults',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
