# Generated by Django 4.2.6 on 2024-01-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_quizs_quizcategories_quizs_quizcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
