# Generated by Django 4.2.6 on 2024-01-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_quizresults_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizs',
            name='duration',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
