# Generated by Django 4.2.6 on 2024-01-27 16:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_quizs_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresults',
            name='isStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizresults',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
