# Generated by Django 4.2.6 on 2024-01-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_quizlobby'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlobby',
            name='questionTime',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
