# Generated by Django 5.0.1 on 2024-01-30 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_quizlobby_questiontime'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlobby',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
