# Generated by Django 5.0.1 on 2024-02-01 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_quizlobby_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlobby',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
    ]
