# Generated by Django 5.0.1 on 2024-02-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_quizlobby_current_question_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizlobby',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
