# Generated by Django 5.0.1 on 2024-02-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_quizlobby_quiz_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlobby',
            name='quiz_completed',
        ),
        migrations.AddField(
            model_name='quizlobby',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
