# Generated by Django 5.0.1 on 2024-02-04 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_remove_quizlobby_quiz_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizlobby',
            name='capacity',
        ),
    ]
